# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: andreas dias
description: personal website
baseurl: ""
url: https://www.andreasdias.com

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: andreas dias
  description:
    - Hello!
    - This tiny website
    - Looks like json
  role: Engineering manager
  # cv: assets/cv.pdf
  address:
    - New York City, NY
  source: https://github.com/piazzai/hacked-jekyll
  profiles:
    linkedin: https://www.linkedin.com/in/andreas-dias
    github: https://github.com/adias9

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
